version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "monthly"
    groups:
      gha:
        patterns:
          - "*"
