name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os:
          # - macos-26
          - ubuntu-24.04
          # - windows-2025

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup Volta
        uses: volta-cli/action@v4.2.1

      - name: Install dependencies
        run: npm ci

      - name: Check for linting errors
        run: npm run lint
      
      # TODO: re enable after adding test coverage for every function.
      # - name: Check for type errors
      #   run: npm run type

      - name: Check for test suite errors
        run: npm run test
